application:
  name: ich bin der kaiser von china tralala tralalla yolo!
  description: lorem ipsum kaczory!
  aleJaJA: 123
  logo: https://img.freepik.com/free-photo/close-up-portrait-beautiful-cat_23-2149214419.jpg
