application:
  name: jasonkrik-test2-staging-sync
  description: jasonkrik-test2-staging-sync to another 5
  aleJaJA: 123
  logo: "https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/552500/ss_70bcfe361ea570b0617f0bf0d2604124f9a263e5.1920x1080.jpg"
deployment:
  branches:
    another:
      label: "Another1"
