application:
  name: jasonkrik-test2-staging-sync
  description: jasonkrik-test2-staging-sync to another
  aleJaJA: 123
  logo: "https://cdn-dkepej.nitrocdn.com/xHPizjaXJNONuYnLnfsGSUCsMnIlzOEq/assets/images/optimized/rev-ef469ea/blog.frame.io/wp-content/uploads/2021/12/lotr-forced-perspective-cart-bilbo-gandalf.jpg"
