version: '3.8'
services:
  nginx:
    image: nginx:main2
    ports:
      - 8089:80
    volumes:
      - ./html5up-stellar/:/usr/share/nginx/html
    environment:
      - STORAGE_TYPE=${THE_STORAGE:-hetzner5}
