version: '3.8'
services:
  nginx:
    image: nginx:2-alpine-another
    ports:
      - 8089:80
    volumes:
      - ./html5up-stellar/:/usr/share/nginx/html
    environment:
      - PROTOCOL=${SOME_OTHER:-yolo}
